const blenders = [
  {
    name: "Ninja Professional Blender",
    brand: "Ninja",
    price: "89.99",
    alt: "Ninja Professional Blender Image",
    img: "",
  },
  {
    name: "Vitamix E310 Explorian",
    brand: "Vitamix",
    price: "349.95",
    alt: "Vitamix E310 Explorian Image",
    img: "",
  },
  {
    name: "Breville BBL620SIL",
    brand: "Breville",
    price: "199.95",
    alt: "Breville BBL620SIL Image",
    img: "",
  },
  {
    name: "Hamilton Beach Power Elite",
    brand: "Hamilton Beach",
    price: "39.99",
    alt: "Hamilton Beach Power Elite Image",
    img: "",
  },
  {
    name: "Oster Pro 1200",
    brand: "Oster",
    price: "99.99",
    alt: "Oster Pro 1200 Image",
    img: "",
  },
  {
    name: "NutriBullet Pro 900",
    brand: "NutriBullet",
    price: "79.99",
    alt: "NutriBullet Pro 900 Image",
    img: "",
  },
  {
    name: "KitchenAid KSB1575ER",
    brand: "KitchenAid",
    price: "129.99",
    alt: "KitchenAid KSB1575ER Image",
    img: "",
  },
  {
    name: "Black+Decker Countertop Blender",
    brand: "Black+Decker",
    price: "34.99",
    alt: "Black+Decker Countertop Blender Image",
    img: "",
  },
  {
    name: "Blendtec Total Classic",
    brand: "Blendtec",
    price: "299.95",
    alt: "Blendtec Total Classic Image",
    img: "",
  },
  {
    name: "Cuisinart CBT-1500",
    brand: "Cuisinart",
    price: "199.00",
    alt: "Cuisinart CBT-1500 Image",
    img: "",
  },
  {
    name: "Aicok Smoothie Blender",
    brand: "Aicok",
    price: "49.99",
    alt: "Aicok Smoothie Blender Image",
    img: "",
  },
  {
    name: "Smeg Blender",
    brand: "Smeg",
    price: "149.95",
    alt: "Smeg Blender Image",
    img: "",
  },
  {
    name: "Braun MultiQuick Hand Blender",
    brand: "Braun",
    price: "79.99",
    alt: "Braun MultiQuick Hand Blender Image",
    img: "",
  },
  {
    name: "Margaritaville Frozen Concoction Maker",
    brand: "Margaritaville",
    price: "299.95",
    alt: "Margaritaville Frozen Concoction Maker Image",
    img: "",
  },
  {
    name: "Philips Avance Collection Blender",
    brand: "Philips",
    price: "199.99",
    alt: "Philips Avance Collection Blender Image",
    img: "",
  },
  {
    name: "Kitchenaid Immersion Blender",
    brand: "KitchenAid",
    price: "69.99",
    alt: "Kitchenaid Immersion Blender Image",
    img: "",
  },
  {
    name: "Cosori Blender",
    brand: "Cosori",
    price: "89.99",
    alt: "Cosori Blender Image",
    img: "",
  },
  {
    name: "Ninja Nutri Pro Compact Blender",
    brand: "Ninja",
    price: "89.99",
    alt: "Ninja Nutri Pro Compact Blender Image",
    img: "",
  },
  {
    name: "Hamilton Beach Personal Blender",
    brand: "Hamilton Beach",
    price: "24.99",
    alt: "Hamilton Beach Personal Blender Image",
    img: "",
  },
];

export { blenders };
