const games = [
  {
    name: "The Witcher 3: Wild Hunt",
    rating: 4.9,
    price: 39.99,
    img: "../images/TW3.png",
    alt: "The Witcher 3: Wild Hunt - Open world RPG game",
  },
  {
    name: "Red Dead Redemption 2",
    rating: 4.8,
    price: 59.99,
    img: "",
    alt: "Red Dead Redemption 2 - Action-adventure western game",
  },
  {
    name: "Cyberpunk 2077",
    rating: 4.4,
    price: 49.99,
    img: "",
    alt: "Cyberpunk 2077 - Open world sci-fi RPG",
  },
  {
    name: "Minecraft",
    rating: 4.7,
    price: 26.99,
    img: "",
    alt: "Minecraft - Sandbox building game",
  },
  {
    name: "The Legend of Zelda: Breath of the Wild",
    rating: 5.0,
    price: 59.99,
    img: "",
    alt: "Zelda: Breath of the Wild - Action-adventure game",
  },
  {
    name: "It Takes Two",
    rating: 4.5,
    price: 1,
    img: "",
    alt: "It takes two",
  },
  {
    name: "Apex Legends",
    rating: 4.6,
    price: 0, // Free game, treated as 0
    img: "",
    alt: "Apex Legends - Battle royale shooter",
  },
  {
    name: "Call of Duty: Modern Warfare II",
    rating: 4.8,
    price: 69.99,
    img: "",
    alt: "Call of Duty: Modern Warfare II - First-person shooter",
  },
  {
    name: "Assassin's Creed Valhalla",
    rating: 4.6,
    price: 59.99,
    img: "",
    alt: "Assassin's Creed Valhalla - Viking action RPG",
  },
  {
    name: "Hades",
    rating: 4.9,
    price: 24.99,
    img: "",
    alt: "Hades - Rogue-like dungeon crawler",
  },
  {
    name: "Super Mario Odyssey",
    rating: 4.8,
    price: 59.99,
    img: "",
    alt: "Super Mario Odyssey - Platforming adventure game",
  },
  {
    name: "Persona 5 Royal",
    rating: 4.9,
    price: 59.99,
    img: "",
    alt: "Persona 5 Royal - Japanese RPG game",
  },
  {
    name: "Sekiro: Shadows Die Twice",
    rating: 4.8,
    price: 59.99,
    img: "",
    alt: "Sekiro: Shadows Die Twice - Action-adventure with samurai combat",
  },
  {
    name: "Overwatch 2",
    rating: 4.4,
    price: 0, // Free game, treated as 0
    img: "",
    alt: "Overwatch 2 - Team-based first-person shooter",
  },
  {
    name: "Animal Crossing: New Horizons",
    rating: 4.9,
    price: 59.99,
    img: "",
    alt: "Animal Crossing: New Horizons - Life simulation game",
  },
  {
    name: "Dragon Age Inquisitaion",
    rating: 4.7,
    price: 1, // Invalid price, set to NaN
    img: "",
    alt: "Dragon Age Inquisitaion",
  },
  {
    name: "Ghost of Tsushima",
    rating: 4.8,
    price: 59.99,
    img: "",
    alt: "Ghost of Tsushima - Open world action-adventure",
  },
  {
    name: "Resident Evil Village",
    rating: 4.7,
    price: 59.99,
    img: "",
    alt: "Resident Evil Village - Survival horror game",
  },
  {
    name: "Horizon Zero Dawn",
    rating: 4.8,
    price: 49.99,
    img: "",
    alt: "Horizon Zero Dawn - Open-world action RPG",
  },
  {
    name: "Final Fantasy VII Remake",
    rating: 4.8,
    price: 59.99,
    img: "",
    alt: "Final Fantasy VII Remake - Action RPG remake of the classic",
  },
];
export { games };
